quotes = [
  "I don't stop when I'm tired, I stop when I'm done.",
  "Success is not a destination, it's a journey.",
  "The only thing standing between me and my dreams is my work ethic.",
  "I'm not a millionaire yet, but I'm one day closer than yesterday.",
  "If you want to succeed, you have to be willing to outwork everyone else.",
  "I don't believe in luck, I believe in hard work.",
  "Success is not for the lazy.",
  "I don't have time for excuses, only results.",
  "Winners never quit, and quitters never win.",
  "I don't need motivation, I need discipline.",
  "I don't have a 9 to 5, I have a when I wake up to when I go to bed.",
  "I don't take days off, I take days to get better.",
  "I'm not competing with anyone else, I'm competing with my own potential.",
  "I'm not where I want to be, but I'm closer than I was yesterday.",
  "The grind never stops, and neither do I.",
  "I don't have a work-life balance, I have a work-work balance.",
  "Success is not a goal, it's a lifestyle.",
  "I don't wait for opportunities, I create them.",
  "I don't work hard because I have to, I work hard because I want to.",
  "I don't believe in limits, only challenges.",
  "I don't settle for good enough, I strive for excellence.",
  "I don't take shortcuts, I take the long way to success.",
  "I'm not afraid to fail, I'm afraid of not trying.",
  "I don't have an off switch, I have an on and on switch.",
  "I don't work hard for money, I work hard for the impact.",
  "I don't have time for negativity, only positivity.",
  "I don't have a comfort zone, I have a growth zone.",
  "I don't have an alarm clock, I have a dream clock.",
  "I don't have a job, I have a mission.",
  "I don't have a boss, I have a purpose.",
  "I don't have a to-do list, I have a to-conquer list.",
  "I don't have limits, I have opportunities.",
  "I don't take breaks, I take action.",
  "I don't have a schedule, I have a plan.",
  "I don't have a finish line, I have a starting line.",
  "I don't have a retirement plan, I have a passion plan.",
  "I don't have time for regrets, only lessons.",
  "I don't have a ceiling, I have a sky.",
  "I don't have a limit, I have a breakthrough.",
  "I don't have a salary, I have a purpose.",
  "I don't have an exit strategy, I have a legacy plan.",
  "I don't have a plan B, I have a plan A+.",
  "I don't have an excuse, I have a solution.",
  "I don't have a fear of failure, I have a fear of not trying.",
  "I don't have a fear of success, I have a desire for it.",
  "I don't have a doubt, I have a belief.",
  "I don't have a problem, I have an opportunity.",
  "I don't have a mistake, I have a lesson.",
  "I don't have a 9 to 5, I have a 24/7.",
  "I don't have a job, I have a calling.",
  "I don't have a goal, I have a vision.",
  "I don't have an obstacle, I have an opportunity to overcome.",
  "I don't have a team, I have a family.",
  "I don't have a follower count, I have a community.",
  "I don't have a title, I have a purpose.",
  "I don't have a network, I have a tribe.",
  "I don't have a comfort zone, I have a challenge zone.",
  "I don't have a fear of rejection, I have a love of opportunity.",
  "I don't have a fear of criticism, I have a love of growth.",
  "I don't have a fear of change, I have a love of progress.",
  "I don't have a fear of the unknown, I have a love of adventure.",
  "I don't have a fear of hard work, I have a love of success.",
  "I don't have a fear of failure, I have a love of learning.",
  "I don't have a fear of competition, I have a love of improvement.",
  "I don't have a fear of success, I have a love of impact.",
  "I don't have a fear of taking risks, I have a love of innovation.",
  "I don't have a fear of being different, I have a love of individuality.",
  "I don't have a fear of being wrong, I have a love of self-correction.",
  "I don't have a fear of being judged, I have a love of authenticity.",
  "I don't have a fear of failure, I have a respect for the journey.",
  "I don't have a fear of starting small, I have a respect for the process.",
  "I don't have a fear of setbacks, I have a respect for resilience.",
  "I don't have a fear of adversity, I have a respect for strength.",
  "I don't have a fear of criticism, I have a respect for feedback.",
  "I don't have a fear of challenges, I have a respect for growth.",
  "I don't have a fear of hard work, I have a respect for results.",
  "I don't have a fear of obstacles, I have a respect for determination.",
  "I don't have a fear of rejection, I have a respect for perseverance.",
  "I don't have a fear of failure, I have a respect for success.",
  "I don't have a fear of competition, I have a respect for excellence.",
  "I don't have a fear of risk, I have a respect for innovation.",
  "I don't have a fear of being different, I have a respect for uniqueness.",
  "I don't have a fear of being wrong, I have a respect for improvement.",
  "I don't have a fear of being judged, I have a respect for authenticity.",
  "I don't have a fear of starting over, I have a respect for reinvention.",
  "I don't have a fear of uncertainty, I have a respect for adventure.",
  "I don't have a fear of hard times, I have a respect for perseverance.",
  "I don't have a fear of change, I have a respect for evolution.",
  "I don't have a fear of the future, I have a respect for preparation.",
  "I don't have a limit, I have a breakthrough waiting to happen.",
  "I don't have a failure, I have a lesson learned.",
  "I don't have a weakness, I have an area for improvement.",
  "I don't have a problem, I have a challenge to conquer.",
  "I don't have an excuse, I have a reason to push harder.",
  "I don't have a complaint, I have a solution to find.",
  "I don't have a comfort zone, I have a zone of discomfort to expand.",
  "I don't have a clock, I have a stopwatch to beat.",
  "I don't have a status quo, I have a new standard to set.",
  "I don't have a comfort zone, I have a laboratory for growth.",
  "I don't have a competitor, I have a partner in progress."
]
